"""Pydantic schemas for structured data validation."""

from enum import Enum
from typing import Optional, List, Dict, Any, Literal
from pydantic import BaseModel, Field


# ============================================================
# PARSER SCHEMAS
# ============================================================

class PaperSpecification(BaseModel):
    """Structured paper specification extracted by Parser agent."""

    title: str = Field(..., description="Paper title")
    authors: List[str] = Field(default_factory=list)
    abstract: str = Field(default="")

    problem_definition: str = Field(default="unspecified")

    architecture: Dict[str, Any] = Field(
        default_factory=dict,
        description="Model architecture details (layers, components, etc.)"
    )

    hyperparameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Training hyperparameters (lr, batch_size, epochs, optimizer, etc.)"
    )

    dataset: Dict[str, Any] = Field(
        default_factory=dict,
        description="Dataset information (name, preprocessing, splits)"
    )

    evaluation: Dict[str, Any] = Field(
        default_factory=dict,
        description="Evaluation methodology and metrics"
    )

    claimed_results: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Reported metrics from the paper"
    )

    baselines: List[str] = Field(default_factory=list)
    ablations: List[str] = Field(default_factory=list)

    equations: List[str] = Field(
        default_factory=list,
        description="Important equations extracted from paper"
    )

    ambiguities: List[str] = Field(
        default_factory=list,
        description="Missing or ambiguous information"
    )

    implementation_notes: str = Field(default="")


class ParserOutput(BaseModel):
    """Output from Parser agent."""
    success: bool
    specification: Optional[PaperSpecification] = None
    error: Optional[str] = None
    extraction_metadata: Dict[str, Any] = Field(default_factory=dict)


# ============================================================
# PLANNER SCHEMAS
# ============================================================

class ImplementationPlan(BaseModel):
    """Implementation plan generated by Planner agent."""

    project_structure: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Required directories and files"
    )

    dependencies: List[str] = Field(
        default_factory=list,
        description="Python packages required"
    )

    model_implementation: Dict[str, Any] = Field(
        default_factory=dict,
        description="Model architecture implementation details"
    )

    dataset_pipeline: Dict[str, Any] = Field(
        default_factory=dict,
        description="Dataset loading and preprocessing steps"
    )

    training_loop: Dict[str, Any] = Field(
        default_factory=dict,
        description="Training loop configuration"
    )

    evaluation_loop: Dict[str, Any] = Field(
        default_factory=dict,
        description="Evaluation procedure"
    )

    metrics_to_capture: List[str] = Field(
        default_factory=list,
        description="Metrics that must be logged"
    )

    reproducibility_requirements: Dict[str, Any] = Field(
        default_factory=dict,
        description="Random seeds, deterministic operations, etc."
    )

    computational_requirements: Dict[str, Any] = Field(
        default_factory=dict,
        description="Expected runtime, memory, CPU/GPU needs"
    )

    specified_by_paper: List[str] = Field(
        default_factory=list,
        description="Elements directly specified in paper"
    )

    inferred: List[str] = Field(
        default_factory=list,
        description="Elements inferred from common practices"
    )

    assumptions: List[str] = Field(
        default_factory=list,
        description="Assumptions being made"
    )


class PlannerOutput(BaseModel):
    """Output from Planner agent."""
    success: bool
    plan: Optional[ImplementationPlan] = None
    error: Optional[str] = None


# ============================================================
# CODEGEN SCHEMAS
# ============================================================

class GeneratedFile(BaseModel):
    """A single generated file."""
    path: str = Field(..., description="Relative path in generated workspace")
    content: str = Field(..., description="File contents")
    purpose: str = Field(..., description="What this file does")


class GeneratedImplementation(BaseModel):
    """Complete generated implementation."""

    files: List[GeneratedFile] = Field(
        default_factory=list,
        description="All generated files"
    )

    entry_point: str = Field(
        ...,
        description="Main script to execute (e.g., 'train.py')"
    )

    requirements: List[str] = Field(
        default_factory=list,
        description="Python dependencies"
    )

    setup_instructions: str = Field(default="")
    run_instructions: str = Field(default="")

    configuration: Dict[str, Any] = Field(
        default_factory=dict,
        description="Runtime configuration values"
    )


class CodegenOutput(BaseModel):
    """Output from Codegen agent."""
    success: bool
    implementation: Optional[GeneratedImplementation] = None
    workspace_path: Optional[str] = None
    error: Optional[str] = None


# ============================================================
# EXECUTOR SCHEMAS
# ============================================================

class ExecutionResult(BaseModel):
    """Result of code execution in sandbox."""

    status: Literal["success", "failure", "timeout", "error"]
    exit_code: int

    runtime_seconds: float

    stdout: str = Field(default="")
    stderr: str = Field(default="")

    metrics: Dict[str, Any] = Field(
        default_factory=dict,
        description="Captured metrics (accuracy, loss, etc.)"
    )

    artifacts: List[str] = Field(
        default_factory=list,
        description="Generated artifacts (model weights, plots, etc.)"
    )

    resource_usage: Dict[str, Any] = Field(
        default_factory=dict,
        description="CPU, memory usage during execution"
    )

    error: Optional[str] = None
    error_traceback: Optional[str] = None


class ExecutorOutput(BaseModel):
    """Output from Executor agent."""
    success: bool
    result: Optional[ExecutionResult] = None
    error: Optional[str] = None


# ============================================================
# VERIFIER SCHEMAS
# ============================================================

class MetricComparison(BaseModel):
    """Comparison of a single metric."""

    metric_name: str
    claimed_value: Optional[float] = None
    reproduced_value: Optional[float] = None

    absolute_difference: Optional[float] = None
    relative_difference: Optional[float] = None

    tolerance: float = Field(default=0.02)
    status: Literal["PASS", "FAIL", "UNKNOWN"]

    notes: str = Field(default="")


class DiscrepancyCategory(str, Enum):
    """Categories of reproduction discrepancies."""
    ARCHITECTURE_MISMATCH = "architecture_mismatch"
    HYPERPARAMETER_MISMATCH = "hyperparameter_mismatch"
    DATASET_MISMATCH = "dataset_mismatch"
    PREPROCESSING_MISMATCH = "preprocessing_mismatch"
    RANDOM_SEED_VARIANCE = "random_seed_variance"
    MISSING_IMPLEMENTATION_DETAIL = "missing_implementation_detail"
    TRAINING_INSTABILITY = "training_instability"
    COMPUTATIONAL_LIMITATION = "computational_limitation"
    CODE_EXECUTION_FAILURE = "code_execution_failure"
    PAPER_AMBIGUITY = "paper_ambiguity"


class ReproducibilityVerdict(str, Enum):
    """Overall reproducibility status."""
    SUCCESSFUL = "successful"
    PARTIAL = "partial"
    FAILED = "failed"
    EXECUTION_FAILED = "execution_failed"
    INSUFFICIENT_INFO = "insufficient_info"


class VerificationReport(BaseModel):
    """Complete verification report."""

    verdict: ReproducibilityVerdict

    metric_comparisons: List[MetricComparison] = Field(default_factory=list)

    discrepancies: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Identified discrepancies with categories"
    )

    summary: str = Field(default="")

    reproduction_quality_score: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="0-1 score of reproduction quality"
    )


class VerifierOutput(BaseModel):
    """Output from Verifier agent."""
    success: bool
    report: Optional[VerificationReport] = None
    error: Optional[str] = None


# ============================================================
# API REQUEST/RESPONSE SCHEMAS
# ============================================================

class ReproductionRequest(BaseModel):
    """Request to start reproduction pipeline."""
    paper_source: str = Field(
        ...,
        description="PDF file path or arXiv URL"
    )
    paper_title: Optional[str] = None


class ReproductionResponse(BaseModel):
    """Response from starting reproduction."""
    pipeline_id: str
    status: str
    message: str


class PipelineStatusResponse(BaseModel):
    """Pipeline status response."""
    pipeline_id: str
    status: str
    current_stage: str
    retry_count: int
    created_at: str
    updated_at: str
    error: Optional[str] = None
